name: accessibility-checker-mmd

services:
  web_server:
    build: ./nginx/
    ports:
      - 8000:80

    volumes:
      - ./accessibility-checker-api/:/var/www/html/

  php:
    build: ./accessibility-checker-api/
    expose:
      - 9000

  react:
    build: ./accessibility-checker/
    ports:
      - 5173:5173

    develop:
      watch:
        - action: sync
          path: ./accessibility-checker/src/
          target: /usr/accessibility-checker/src/

    